# Generated by Django 3.1.3 on 2020-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='bookshelf',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
