# Generated by Django 3.1.3 on 2020-12-01 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0002_auto_20201130_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('aliases', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('birth_year', models.IntegerField(null=True)),
                ('death_year', models.IntegerField(null=True)),
                ('wikipedia_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('repo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(db_index=True, default='', max_length=1000)),
                ('language', models.CharField(db_index=True, default='en', max_length=5)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('gutenberg_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('gutenberg_bookshelf', models.CharField(default='', max_length=1000)),
                ('subjects', models.CharField(default='', max_length=1000)),
                ('full_text', models.TextField(blank=True, default='', null=True)),
                ('num_downloads', models.IntegerField(default=0)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('yaml', models.TextField(default='', null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mgmt.author')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
