# Generated by Django 3.1.3 on 2020-12-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0003_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='gutenberg_bookshelf',
        ),
        migrations.RemoveField(
            model_name='book',
            name='gutenberg_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.RemoveField(
            model_name='book',
            name='num_downloads',
        ),
        migrations.RemoveField(
            model_name='book',
            name='repo_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='book',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='book',
            name='yaml',
        ),
        migrations.AddField(
            model_name='book',
            name='copyrighted',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='downloads',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='filemask',
            field=models.CharField(default='', max_length=240),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='gutindex',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='nonfiling',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='updatemode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
