# Generated by Django 3.1.3 on 2020-12-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0005_auto_20201201_2149'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
    ]
