# Generated by Django 3.1.3 on 2020-12-01 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0006_auto_20201201_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
